### ISSUE TITLE
Create users functions and updating events

### ISSUE THREAD

**Issue by vmleroy** [prof-hasan/tp-web-eventos#8]
- Inside `packages/domain-events/user`:
  - Create types
  - Create adapters
  - Create requisitions (data)
  - Update events types
  - Update events adapters
  - Update events requisitions (data)

- Test

**Comment by vnszero** [comment]
- Create the migration in supabase
- Inside `packages/domain-events/user
- [ ] Create the types
- [ ] Create the adapters
- [ ] Create request functions in the table (date)
- Test
